import { CardData } from './card-provider';

let dummy = 999999;

export const cardTestData: CardData[] = [
  {
    uuid: (dummy++).toString(),
    title: 'Luxury Suite at Marriott',
    imageUrl: '',
    text: 'Experience the ultimate comfort and relaxation in our spacious luxury suite at Marriott.',
    price: '$800',
    addedat: new Date('2024-06-11'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Standard Room at Hilton',
    imageUrl: '',
    text: 'Enjoy a comfortable stay in our standard room at Hilton, perfect for business or leisure.',
    price: '$250',
    addedat: new Date('2024-03-05'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Ocean View Room at Hyatt',
    imageUrl: '',
    text: 'Wake up to stunning ocean views in our luxurious ocean view room at Hyatt.',
    price: '$700',
    addedat: new Date('2024-09-22'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Penthouse Suite at Ritz-Carlton',
    imageUrl: '',
    text: 'Indulge in luxury in our spacious penthouse suite at Ritz-Carlton, complete with breathtaking city views.',
    price: '$1000',
    addedat: new Date('2024-05-18'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Deluxe Room at Four Seasons',
    imageUrl: '',
    text: 'Experience unparalleled comfort and luxury in our deluxe room at Four Seasons.',
    price: '$600',
    addedat: new Date('2024-07-14'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Beachfront Villa at Fairmont',
    imageUrl: '',
    text: 'Relax and unwind in our luxurious beachfront villa at Fairmont, with stunning views of the ocean.',
    price: '$900',
    addedat: new Date('2024-08-30'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Junior Suite at W Hotel',
    imageUrl: '',
    text: 'Experience modern luxury in our stylish junior suite at W Hotel, with vibrant city views.',
    price: '$400',
    addedat: new Date('2024-02-20'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Family Room at Westin',
    imageUrl: '',
    text: 'Enjoy a comfortable and spacious stay in our family room at Westin, perfect for family vacations.',
    price: '$350',
    addedat: new Date('2024-11-05'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Presidential Suite at InterContinental',
    imageUrl: '',
    text: 'Experience the height of luxury in our opulent presidential suite at InterContinental.',
    price: '$950',
    addedat: new Date('2024-04-02'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Mountain View Room at Park Hyatt',
    imageUrl: '',
    text: 'Enjoy breathtaking views of the mountains in our elegant mountain view room at Park Hyatt.',
    price: '$500',
    addedat: new Date('2024-10-10'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Deluxe Room at Hilton',
    imageUrl: '',
    text: 'Experience the ultimate comfort in our deluxe room at Hilton, with modern amenities and stunning decor.',
    price: '$250',
    addedat: new Date('2024-06-15'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Luxury Suite at Mandarin Oriental',
    imageUrl: '',
    text: 'Indulge in luxury in our spacious and elegant luxury suite at Mandarin Oriental.',
    price: '$800',
    addedat: new Date('2024-09-25'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Boutique Room at The Standard',
    imageUrl: '',
    text: 'Discover our unique and stylish boutique room at The Standard, with vibrant decor and top-notch amenities.',
    price: '$300',
    addedat: new Date('2024-07-12'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Penthouse Suite at Ritz Carlton',
    imageUrl: '',
    text: 'Live like royalty in our luxurious penthouse suite at Ritz Carlton, with breathtaking city views and exquisite decor.',
    price: '$1000',
    addedat: new Date('2024-03-08'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Ocean View Room at Four Seasons',
    imageUrl: '',
    text: 'Wake up to stunning views of the ocean in our elegant ocean view room at Four Seasons, with top-class amenities and service.',
    price: '$600',
    addedat: new Date('2024-12-01'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Grand Suite at Waldorf Astoria',
    imageUrl: '',
    text: 'Experience the height of luxury in our grand suite at Waldorf Astoria, with opulent decor and breathtaking city views.',
    price: '$900',
    addedat: new Date('2024-04-20'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Classic Room at Hyatt Regency',
    imageUrl: '',
    text: 'Stay in our classic room at Hyatt Regency, with comfortable furnishings and modern amenities.',
    price: '$200',
    addedat: new Date('2024-08-05'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Junior Suite at Le Meridien',
    imageUrl: '',
    text: 'Experience modern luxury in our stylish junior suite at Le Meridien, with panoramic city views and top-notch amenities.',
    price: '$400',
    addedat: new Date('2024-11-15'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Mountain Retreat at Aman',
    imageUrl: '',
    text: 'Escape to our secluded mountain retreat at Aman, with rustic charm and stunning natural beauty.',
    price: '$800',
    addedat: new Date('2024-05-10'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Pool View Room at Marriott',
    imageUrl: '',
    text: 'Relax and unwind in our serene pool view room at Marriott, with beautiful views and comfortable furnishings.',
    price: '$300',
    addedat: new Date('2024-10-20'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Beachfront Villa at St. Regis',
    imageUrl: '',
    text: 'Enjoy paradise in our luxurious beachfront villa at St. Regis, with private pool and stunning ocean views.',
    price: '$1000',
    addedat: new Date('2024-02-14'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Art Deco Room at The Fontainebleau',
    imageUrl: '',
    text: 'Step back in time in our Art Deco room at The Fontainebleau, with iconic style and modern amenities.',
    price: '$400',
    addedat: new Date('2024-09-01'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Executive Suite at Shangri-La',
    imageUrl: '',
    text: 'Experience unparalleled luxury in our spacious executive suite at Shangri-La, with stunning city views and top-class amenities.',
    price: '$700',
    addedat: new Date('2024-07-30'),
    minipic: '',
  },
  {
    uuid: (dummy++).toString(),
    title: 'Cottage Room at The Ritz-Carlton',
    imageUrl: '',
    text: 'Experience rustic charm in our cozy cottage room at The Ritz-Carlton, with comfortable furnishings and beautiful natural surroundings.',
    price: '$300',
    addedat: new Date('2024-12-10'),
    minipic: '',
  },
];
