name: CI

on: push

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    if: ${{ github.event.repository.owner.login == github.actor }}
    env:
      CYPRESS_BASE_URL: 'http://localhost:5999'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Strict checks
        run: npm run check-strict
      - name: Build code
        run: npm run build
      - name: Test
        run: npm run coverage
      - name: Start test server
        run: nohup npm run test:startserver > /dev/null 2>&1 & echo $! > test-server.pid
      - name: Run Cypress
        run: sleep 10s && npm run test:e2e
      - name: Stop test server
        if: always()
        run: -kill $(cat test-server.pid)
      - name: Sonarqube
        run: npm run sonar
