name: CI

on: push

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64]
    if: ${{ github.event.repository.owner.login == github.actor }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Strict checks
        run: npm run check-strict
      - name: Build dev and prod code
        run: npm run build
      - name: Unit Test
        run: npm run coverage:jest

  test-dev:
    runs-on: [self-hosted, linux, x64]
    needs: build-and-test
    env:
      CYPRESS_BASE_URL: 'http://localhost:5999'
    steps:
      - name: Start test Dev server
        run: nohup npm run ci:startserver-dev > /dev/null 2>&1 & echo $! > dev-test-server.pid
      - name: Run Cypress
        run: sleep 5s && npm run test:e2e
      - name: Stop test server
        if: always()
        run: pkill -F dev-test-server.pid || true

  test-prod:
    runs-on: [self-hosted, linux, x64]
    needs: [build-and-test, test-dev]
    env:
      CYPRESS_BASE_URL: 'http://localhost:5998'
    steps:
      - name: Start test prod server
        run: nohup npm run ci:startserver-prod > /dev/null 2>&1 & echo $! > prod-test-server.pid
      - name: Run Cypress
        run: sleep 5s && npm run test:e2e
      - name: Stop test server
        if: always()
        run: pkill -F prod-test-server.pid || true

  sonarqube:
    runs-on: [self-hosted, linux, x64]
    needs: build-and-test
    steps:
      - name: Sonarqube
        run: npm run sonar
