name: CI

on: push

jobs:
  build:
    runs-on: runs-on: [self-hosted, linux, x64]
    if: ${{ github.event.repository.owner.login == github.actor }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
